version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8088:8088"

  db:
    container_name: kcb-interview-db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kcb@2030!.
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: kcb_interview_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - spring-net
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1081:1080"
      - "1025:1025"
networks:
  spring-net:
    driver: bridge
volumes:
  postgres:
    driver: local